### ISSUE TITLE
The SPJ quad kernel

### ISSUE THREAD

**Issue by lwang-astro** [FDPS/PIKG#4]
Do you have an example input for generating the Superparticle quadrupole kernel?

**Comment by subarutaro** [comment]
I think the EPSP kernel of GPLUM is the best sample of quadrupole kernel.
Now PIKG does not support matrix type, so GPLUM generate temporal kernel and replace string to modify for matrix.

https://github.com/YotaIshigaki/GPLUM/blob/master/src/gravity_kernel_EPSP_quad_individual.pikg

**Comment by lwang-astro** [comment]
Thanks. This works.
